version: "3"
services:
#  app:
#    env_file:
#      - .env.development
#    container_name: car_catalog_app
#    restart: always
#    build: .
#    ports:
#      - "3000:3000"
#    links:
#      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: car_catalog, car_catalog_test
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080